/// Flutter icons CastomIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CastomIcons
///      fonts:
///       - asset: fonts/CastomIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CastomIcons {
  CastomIcons._();

  static const _kFontFam = 'CastomIcons';
  static const String? _kFontPkg = null;

  static const IconData arrow_down_icon_215156 = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
